var countryCodePairs = {
'Afghanistan': 'AFG',
'Aland Islands': 'ALA',
'Albania': 'ALB',
'Algeria': 'DZA',
'American Samoa': 'ASM',
'Andorra': 'AND',
'Angola': 'AGO',
'Anguilla': 'AIA',
'Antarctica': 'ATA',
'Antigua and Barbuda': 'ATG',
'Argentina': 'ARG',
'Armenia': 'ARM',
'Aruba': 'ABW',
'Australia': 'AUS',
'Austria': 'AUT',
'Azerbaijan': 'AZE',
'Bahamas': 'BHS',
'Bahrain': 'BHR',
'Bangladesh': 'BGD',
'Barbados': 'BRB',
'Belarus': 'BLR',
'Belgium': 'BEL',
'Belize': 'BLZ',
'Benin': 'BEN',
'Bermuda': 'BMU',
'Bhutan': 'BTN',
'Bolivia': 'BOL',
'Bosnia and Herzegovina': 'BIH',
'Botswana': 'BWA',
'Bouvet Island': 'BVT',
'Brazil': 'BRA',
'British Virgin Islands': 'VGB',
'British Indian Ocean Territory': 'IOT',
'Brunei Darussalam': 'BRN',
'Bulgaria': 'BGR',
'Burkina Faso': 'BFA',
'Burundi': 'BDI',
'Cambodia': 'KHM',
'Cameroon': 'CMR',
'Canada': 'CAN',
'Cape Verde': 'CPV',
'Cayman Islands': 'CYM',
'Central African Republic': 'CAF',
'Chad': 'TCD',
'Chile': 'CHL',
'China': 'CHN',
'Hong Kong: Special Administrative Region of China': 'HKG',
'Macao: Special Administrative Region of China': 'MAC',
'Christmas Island': 'CXR',
'Cocos (Keeling) Islands': 'CCK',
'Colombia': 'COL',
'Comoros': 'COM',
'Congo': 'COG',
'Democratic Republic of Congo': 'COD',
'Cook Islands': 'COK',
'Costa Rica': 'CRI',
'Ivory Coast': 'CIV',
'Croatia': 'HRV',
'Cuba': 'CUB',
'Cyprus': 'CYP',
'Czech Republic': 'CZE',
'Denmark': 'DNK',
'Djibouti': 'DJI',
'Dominica': 'DMA',
'Dominican Republic': 'DOM',
'Ecuador': 'ECU',
'Egypt': 'EGY',
'El Salvador': 'SLV',
'Equatorial Guinea': 'GNQ',
'Eritrea': 'ERI',
'Estonia': 'EST',
'Ethiopia': 'ETH',
'Falkland Islands (Malvinas)': 'FLK',
'Faroe Islands': 'FRO',
'Fiji': 'FJI',
'Finland': 'FIN',
'France': 'FRA',
'French Guiana': 'GUF',
'French Polynesia': 'PYF',
'French Southern Territories': 'ATF',
'Gabon': 'GAB',
'Gambia': 'GMB',
'Georgia': 'GEO',
'Germany': 'DEU',
'Ghana': 'GHA',
'Gibraltar': 'GIB',
'Greece': 'GRC',
'Greenland': 'GRL',
'Grenada': 'GRD',
'Guadeloupe': 'GLP',
'Guam': 'GUM',
'Guatemala': 'GTM',
'Guernsey': 'GGY',
'Guinea': 'GIN',
'Guinea-Bissau': 'GNB',
'Guyana': 'GUY',
'Haiti': 'HTI',
'Heard Island and Mcdonald Islands': 'HMD',
'Holy See (Vatican City State)': 'VAT',
'Honduras': 'HND',
'Hungary': 'HUN',
'Iceland': 'ISL',
'India': 'IND',
'Indonesia': 'IDN',
'Iran': 'IRN',
'Iraq': 'IRQ',
'Ireland': 'IRL',
'Isle of Man': 'IMN',
'Israel': 'ISR',
'Italy': 'ITA',
'Jamaica': 'JAM',
'Japan': 'JPN',
'Jersey': 'JEY',
'Jordan': 'JOR',
'Kazakhstan': 'KAZ',
'Kenya': 'KEN',
'Kiribati': 'KIR',
'Korea: Democratic Peoples Republic of': 'PRK',
'South Korea': 'KOR',
'Kuwait': 'KWT',
'Kyrgyzstan': 'KGZ',
'Laos': 'LAO',
'Latvia': 'LVA',
'Lebanon': 'LBN',
'Lesotho': 'LSO',
'Liberia': 'LBR',
'Libya': 'LBY',
'Liechtenstein': 'LIE',
'Lithuania': 'LTU',
'Luxembourg': 'LUX',
'Macedonia: Republic of': 'MKD',
'Madagascar': 'MDG',
'Malawi': 'MWI',
'Malaysia': 'MYS',
'Maldives': 'MDV',
'Mali': 'MLI',
'Malta': 'MLT',
'Marshall Islands': 'MHL',
'Martinique': 'MTQ',
'Mauritania': 'MRT',
'Mauritius': 'MUS',
'Mayotte': 'MYT',
'Mexico': 'MEX',
'Micronesia: Federated States of': 'FSM',
'Moldova': 'MDA',
'Monaco': 'MCO',
'Mongolia': 'MNG',
'Montenegro': 'MNE',
'Montserrat': 'MSR',
'Morocco': 'MAR',
'Mozambique': 'MOZ',
'Myanmar': 'MMR',
'Namibia': 'NAM',
'Nauru': 'NRU',
'Nepal': 'NPL',
'Netherlands': 'NLD',
'Netherlands Antilles': 'ANT',
'New Caledonia': 'NCL',
'New Zealand': 'NZL',
'Nicaragua': 'NIC',
'Niger': 'NER',
'Nigeria': 'NGA',
'Niue': 'NIU',
'Norfolk Island': 'NFK',
'Northern Mariana Islands': 'MNP',
'Norway': 'NOR',
'Oman': 'OMN',
'Pakistan': 'PAK',
'Palau': 'PLW',
'Palestinian Authority': 'PSE',
'Panama': 'PAN',
'Papua New Guinea': 'PNG',
'Paraguay': 'PRY',
'Peru': 'PER',
'Philippines': 'PHL',
'Pitcairn': 'PCN',
'Poland': 'POL',
'Portugal': 'PRT',
'Puerto Rico': 'PRI',
'Qatar': 'QAT',
'Réunion': 'REU',
'Romania': 'ROU',
'Russia': 'RUS',
'Rwanda': 'RWA',
'Saint-Barthélemy': 'BLM',
'Saint Helena': 'SHN',
'Saint Kitts and Nevis': 'KNA',
'Saint Lucia': 'LCA',
'Saint-Martin (French part)': 'MAF',
'Saint Pierre and Miquelon': 'SPM',
'Saint Vincent and Grenadines': 'VCT',
'Samoa': 'WSM',
'San Marino': 'SMR',
'Sao Tome and Principe': 'STP',
'Saudi Arabia': 'SAU',
'Senegal': 'SEN',
'Serbia': 'SRB',
'Seychelles': 'SYC',
'Sierra Leone': 'SLE',
'Singapore': 'SGP',
'Slovak Republic': 'SVK',
'Slovenia': 'SVN',
'Solomon Islands': 'SLB',
'Somalia': 'SOM',
'South Africa': 'ZAF',
'South Georgia and the South Sandwich Islands': 'SGS',
'South Sudan': 'SSD',
'Spain': 'ESP',
'Sri Lanka': 'LKA',
'Sudan': 'SDN',
'Suriname *': 'SUR',
'Svalbard and Jan Mayen Islands': 'SJM',
'Swaziland': 'SWZ',
'Sweden': 'SWE',
'Switzerland': 'CHE',
'Syria': 'SYR',
'Taiwan': 'TWN',
'Tajikistan': 'TJK',
'Tanzania *: United Republic of': 'TZA',
'Thailand': 'THA',
'Timor-Leste': 'TLS',
'Togo': 'TGO',
'Tokelau': 'TKL',
'Tonga': 'TON',
'Trinidad and Tobago': 'TTO',
'Tunisia': 'TUN',
'Turkey': 'TUR',
'Turkmenistan': 'TKM',
'Turks and Caicos Islands': 'TCA',
'Tuvalu': 'TUV',
'Uganda': 'UGA',
'Ukraine': 'UKR',
'United Arab Emirates': 'ARE',
'United Kingdom': 'GBR',
'United States of America': 'USA',
'United States Minor Outlying Islands': 'UMI',
'Uruguay': 'URY',
'Uzbekistan': 'UZB',
'Vanuatu': 'VUT',
'Venezuela': 'VEN',
'Vietnam': 'VNM',
'Virgin Islands: US': 'VIR',
'Wallis and Futuna Islands': 'WLF',
'Western Sahara': 'ESH',
'Yemen': 'YEM',
'Zambia': 'ZMB',
'Zimbabwe': 'ZWE'
};

var countryNamePairs = {
'Afghanistan' :'Afghanistan',
'Aland Islands' :'Aland Islands',
'Albania' :'Albania',
'Algeria' :'Algeria',
'American Samoa' :'American Samoa',
'Andorra' :'Andorra',
'Angola' :'Angola',
'Anguilla' :'Anguilla',
'Antarctica' :'Antarctica',
'Antigua and Barbuda' :'Antigua and Barbuda',
'Argentina' :'Argentina',
'Armenia' :'Armenia',
'Aruba' :'Aruba',
'Australia' :'Australia',
'Austria' :'Austria',
'Azerbaijan' :'Azerbaijan',
'Bahamas' :'Bahamas',
'Bahrain' :'Bahrain',
'Bangladesh' :'Bangladesh',
'Barbados' :'Barbados',
'Belarus' :'Belarus',
'Belgium' :'Belgium',
'Belize' :'Belize',
'Benin' :'Benin',
'Bermuda' :'Bermuda',
'Bhutan' :'Bhutan',
'Bolivia' :'Bolivia',
'Bosnia and Herzegovina' :'Bosnia and Herzegovina',
'Botswana' :'Botswana',
'Bouvet Island' :'Bouvet Island',
'Brazil' :'Brazil',
'British Virgin Islands' :'British Virgin Islands',
'British Indian Ocean Territory' :'British Indian Ocean Territory',
'Brunei Darussalam' :'Brunei Darussalam',
'Bulgaria' :'Bulgaria',
'Burkina Faso' :'Burkina Faso',
'Burundi' :'Burundi',
'Cambodia' :'Cambodia',
'Cameroon' :'Cameroon',
'Canada' :'Canada',
'Cape Verde' :'Cape Verde',
'Cayman Islands' :'Cayman Islands',
'Central African Republic' :'Central African Republic',
'Chad' :'Chad',
'Chile' :'Chile',
'China' :'China',
'Hong Kong: Special Administrative Region of China' :'Hong Kong: Special Administrative Region of China',
'Macao: Special Administrative Region of China' :'Macao: Special Administrative Region of China',
'Christmas Island' :'Christmas Island',
'Cocos (Keeling) Islands' :'Cocos (Keeling) Islands',
'Colombia' :'Colombia',
'Comoros' :'Comoros',
'Republic of the Congo' :'Congo',
'Democratic Republic of the Congo' :'Democratic Republic of Congo',
'Cook Islands' :'Cook Islands',
'Costa Rica' :'Costa Rica',
'Ivory Coast' :'Ivory Coast',
'Croatia' :'Croatia',
'Cuba' :'Cuba',
'Cyprus' :'Cyprus',
'Czech Republic' :'Czech Republic',
'Denmark' :'Denmark',
'Djibouti' :'Djibouti',
'Dominica' :'Dominica',
'Dominican Republic' :'Dominican Republic',
'Ecuador' :'Ecuador',
'Egypt' :'Egypt',
'El Salvador' :'El Salvador',
'Equatorial Guinea' :'Equatorial Guinea',
'Eritrea' :'Eritrea',
'Estonia' :'Estonia',
'Ethiopia' :'Ethiopia',
'Falkland Islands (Malvinas)' :'Falkland Islands (Malvinas)',
'Faroe Islands' :'Faroe Islands',
'Fiji' :'Fiji',
'Finland' :'Finland',
'France' :'France',
'French Guiana' :'French Guiana',
'French Polynesia' :'French Polynesia',
'French Southern Territories' :'French Southern Territories',
'Gabon' :'Gabon',
'Gambia' :'Gambia',
'Georgia' :'Georgia',
'Germany' :'Germany',
'Ghana' :'Ghana',
'Gibraltar' :'Gibraltar',
'Greece' :'Greece',
'Greenland' :'Greenland',
'Grenada' :'Grenada',
'Guadeloupe' :'Guadeloupe',
'Guam' :'Guam',
'Guatemala' :'Guatemala',
'Guernsey' :'Guernsey',
'Guinea' :'Guinea',
'Guinea-Bissau' :'Guinea-Bissau',
'Guyana' :'Guyana',
'Haiti' :'Haiti',
'Heard Island and Mcdonald Islands' :'Heard Island and Mcdonald Islands',
'Holy See (Vatican City State)' :'Holy See (Vatican City State)',
'Honduras' :'Honduras',
'Hungary' :'Hungary',
'Iceland' :'Iceland',
'India' :'India',
'Indonesia' :'Indonesia',
'Iran' :'Iran',
'Iraq' :'Iraq',
'Ireland' :'Ireland',
'Isle of Man' :'Isle of Man',
'Israel' :'Israel',
'Italy' :'Italy',
'Jamaica' :'Jamaica',
'Japan' :'Japan',
'Jersey' :'Jersey',
'Jordan' :'Jordan',
'Kazakhstan' :'Kazakhstan',
'Kenya' :'Kenya',
'Kiribati' :'Kiribati',
'Korea: Democratic Peoples Republic of' :'Korea: Democratic Peoples Republic of',
'South Korea' :'South Korea',
'Kuwait' :'Kuwait',
'Kyrgyzstan' :'Kyrgyzstan',
'Laos' :'Laos',
'Latvia' :'Latvia',
'Lebanon' :'Lebanon',
'Lesotho' :'Lesotho',
'Liberia' :'Liberia',
'Libya' :'Libya',
'Liechtenstein' :'Liechtenstein',
'Lithuania' :'Lithuania',
'Luxembourg' :'Luxembourg',
'Macedonia: Republic of' :'Macedonia: Republic of',
'Madagascar' :'Madagascar',
'Malawi' :'Malawi',
'Malaysia' :'Malaysia',
'Maldives' :'Maldives',
'Mali' :'Mali',
'Malta' :'Malta',
'Marshall Islands' :'Marshall Islands',
'Martinique' :'Martinique',
'Mauritania' :'Mauritania',
'Mauritius' :'Mauritius',
'Mayotte' :'Mayotte',
'Mexico' :'Mexico',
'Micronesia: Federated States of' :'Micronesia: Federated States of',
'Moldova' :'Moldova',
'Monaco' :'Monaco',
'Mongolia' :'Mongolia',
'Montenegro' :'Montenegro',
'Montserrat' :'Montserrat',
'Morocco' :'Morocco',
'Mozambique' :'Mozambique',
'Myanmar' :'Myanmar',
'Namibia' :'Namibia',
'Nauru' :'Nauru',
'Nepal' :'Nepal',
'Netherlands' :'Netherlands',
'Netherlands Antilles' :'Netherlands Antilles',
'New Caledonia' :'New Caledonia',
'New Zealand' :'New Zealand',
'Nicaragua' :'Nicaragua',
'Niger' :'Niger',
'Nigeria' :'Nigeria',
'Niue' :'Niue',
'Norfolk Island' :'Norfolk Island',
'Northern Mariana Islands' :'Northern Mariana Islands',
'Norway' :'Norway',
'Oman' :'Oman',
'Pakistan' :'Pakistan',
'Palau' :'Palau',
'Palestinian Authority' :'Palestinian Authority',
'Panama' :'Panama',
'Papua New Guinea' :'Papua New Guinea',
'Paraguay' :'Paraguay',
'Peru' :'Peru',
'Philippines' :'Philippines',
'Pitcairn' :'Pitcairn',
'Poland' :'Poland',
'Portugal' :'Portugal',
'Puerto Rico' :'Puerto Rico',
'Qatar' :'Qatar',
'Réunion' :'Réunion',
'Romania' :'Romania',
'Russia' :'Russia',
'Rwanda' :'Rwanda',
'Saint-Barthélemy' :'Saint-Barthélemy',
'Saint Helena' :'Saint Helena',
'Saint Kitts and Nevis' :'Saint Kitts and Nevis',
'Saint Lucia' :'Saint Lucia',
'Saint-Martin (French part)' :'Saint-Martin (French part)',
'Saint Pierre and Miquelon' :'Saint Pierre and Miquelon',
'Saint Vincent and Grenadines' :'Saint Vincent and Grenadines',
'Samoa' :'Samoa',
'San Marino' :'San Marino',
'Sao Tome and Principe' :'Sao Tome and Principe',
'Saudi Arabia' :'Saudi Arabia',
'Senegal' :'Senegal',
'Serbia' :'Serbia',
'Seychelles' :'Seychelles',
'Sierra Leone' :'Sierra Leone',
'Singapore' :'Singapore',
'Slovakia' :'Slovak Republic',
'Slovenia' :'Slovenia',
'Solomon Islands' :'Solomon Islands',
'Somalia' :'Somalia',
'South Africa' :'South Africa',
'South Georgia and the South Sandwich Islands' :'South Georgia and the South Sandwich Islands',
'South Sudan' :'South Sudan',
'Spain' :'Spain',
'Sri Lanka' :'Sri Lanka',
'Sudan' :'Sudan',
'Suriname': 'Suriname *',
'Svalbard and Jan Mayen Islands' :'Svalbard and Jan Mayen Islands',
'Swaziland' :'Swaziland',
'Sweden' :'Sweden',
'Switzerland' :'Switzerland',
'Syrian Arab Republic' :'Syria',
'Taiwan' :'Taiwan',
'Tajikistan' :'Tajikistan',
'Tanzania *: United Republic of' :'Tanzania *: United Republic of',
'Thailand' :'Thailand',
'Timor-Leste' :'Timor-Leste',
'Togo' :'Togo',
'Tokelau' :'Tokelau',
'Tonga' :'Tonga',
'Trinidad and Tobago' :'Trinidad and Tobago',
'Tunisia' :'Tunisia',
'Turkey' :'Turkey',
'Turkmenistan' :'Turkmenistan',
'Turks and Caicos Islands' :'Turks and Caicos Islands',
'Tuvalu' :'Tuvalu',
'Uganda' :'Uganda',
'Ukraine' :'Ukraine',
'United Arab Emirates' :'United Arab Emirates',
'United Kingdom' :'United Kingdom',
'United States of America' :'United States of America',
'United States Minor Outlying Islands' :'United States Minor Outlying Islands',
'Uruguay' :'Uruguay',
'Uzbekistan' :'Uzbekistan',
'Vanuatu' :'Vanuatu',
'Venezuela' :'Venezuela',
'Vietnam' :'Vietnam',
'Virgin Islands: US' :'Virgin Islands: US',
'Wallis and Futuna Islands' :'Wallis and Futuna Islands',
'Western Sahara' :'Western Sahara',
'Yemen' :'Yemen',
'Zambia' :'Zambia',
'Zimbabwe' :'Zimbabwe'
};